### ISSUE TITLE
Provide a log of requests

### ISSUE THREAD

**Issue by cbovis** [255kb/mockoon#15]
It would be useful to have a log of API requests that have been received when debugging integrations.

**Comment by zuolinding** [comment]
Mockoon is a very good tool for me 
thanks a lot
and this feature will be better

**Comment by nathanielks** [comment]
I am very pleased with how easy it is to use this! I'd second this issue; I'm working on debugging outgoing requests and this would be invaluable to be able to see what requests are being made and their request bodies.

**Comment by 255kb** [comment]
Thanks for the feedback 😊

Concerning the log of request do you see it at the environment level (log all requests done to localhost:3000 at one place) or on each route, but then where do we log requests done to undefined routes?

**Comment by nathanielks** [comment]
I'd submit on the environment level first :)

**Comment by 255kb** [comment]
This will be in the next release (in August probably). It will catch all requests made to an environment and indicate if they have been catched or not by a route.
It will also show headers, params and body like in Chrome debugger 😃
