### ISSUE TITLE
Proxy absent routes

### ISSUE THREAD

**Issue by Lindsor** [255kb/mockoon#17]
We should be able to setup route to proxy to a real api.

ie:

In mockoon we setup `GET: localhost:3000/get/url` will be proxied to `GET: https://www.google.com/get/url`

That way we can mock only SOME endpoints instead of an all or nothing aproach

**Comment by Radwan-AbuOdeh** [comment]
I strongly agree on this feature, mapping domains to mocked servers' APIs would really be a strong feature, It will save time instead of going through your codebase and replace existing API endpoints with the mocked ones.

**Comment by 255kb** [comment]
@Radwan-AbuOdeh It's coming soon in v0.3.0 :)

**Comment by Lindsor** [comment]
That's awesome @255kb this was the only feature missing keeping me from fully using mockoon.

**Comment by 255kb** [comment]
@Lindsor It's will be very useful for me too! Basically what I did is that after launching all your routes defined in Mockoon, there is a catch-all redirecting all requests to the URL you set up. That's it. So normally it's very easy to use and flexible.

**Comment by 255kb** [comment]
v0.3.0-beta is out with this feature ("proxy mode") let me know if everything is working, I did not test all cases but it should work most of the time.
