### ISSUE TITLE
Request: Be explicit about the analytic data collected

### ISSUE THREAD

**Issue by Joshfindit** [255kb/mockoon#18]
The FAQ currently states

```
Yes, but only anonymous data through Google Analytics, with
some very basic metrics like: number of environments and routes
you have, actions done in the application (route select, server started, etc).
```

Suggest showing an example (of all possible collected data) in-line or directly linking to an example submission.

When talking about being tracked, both commercial and residential users **must** be wary of ambiguity.

**Comment by 255kb** [comment]
@Joshfindit Sure, this makes perfectly sense. I will add more details, but also I plan to add an opt out setting in the application. At first install user will be warned about the data collection.
