### ISSUE TITLE
Proxy recording / snapshotting

### ISSUE THREAD

**Issue by baptistemanson** [255kb/mockoon#21]
It would be wonderful if I can configure a url, and proxify all calls from a mockoon server to that other server.
Then the mockoon server would replay what it recorded as pairs of requests/responses, like mountebank.

Use case? 

- I developed an API and I have to mock it for a frontend team afterwards.
- I mocked an API, but it changed, so I want a way to retrofit mockoon fast.

**Comment by 255kb** [comment]
While this would be a nice feature I think it is out of scope of what I want Mockoon to be. 
There is already a proxy mode, but I want to focus on mocking only and keep the tool light and easy to use. 
I will close this for now and if the topic comes back later maybe consider the possibility to add such feature.

**Comment by omanizer** [comment]
I was just about to suggest this same thing and found this old request.  I just spent the last hour creating mock endpoints based on requests that were made through the proxy.  I have a long plane flight over the ocean today and want to be able to work on on a project while not having internet access.  Mocking the API is a great option for doing this.

My current workflow to do this is to open mockoon in proxy mode toward my API, watch the HTTP response in chrome and copy all of the JSON into the response box in mockoon.

If the environment log had a simple "Create Mock From This Request" button it would have saved me a fair bit of time right now and in the future when I face this same problem.

I can see your case for simplicity, but I would argue that this feature is right in line with what you said above by focusing on mocking only.  This is simply an easier way to mock an endpoint and is a great way to eliminate some very repetitive work.

**Comment by digeomel** [comment]
It's a pity this was never implemented, we have the exact same need as described above. I'm looking now into polly.js to see if it's any better/easier, but it doesn't come with a gui.

**Comment by 255kb** [comment]
> It's a pity this was never implemented, we have the exact same need as described above. I'm looking now into polly.js to see if it's any better/easier, but it doesn't come with a gui.

Recording has been implemented in [v3.1.0](https://mockoon.com/releases/3.1.0/#desktop-application). Coupled to the proxy, it allows you to create endpoint from the proxied responses.

**Comment by digeomel** [comment]
@255kb I tried to use the proxy and the recording option, but it is unclear to me how to set it up correctly.

First I imported a json file from our Swagger API to create a new environment will all calls in mockoon. Then I set up the proxy to point to our actual API server, I enable recording, and then... what? I couldn't get the calls to be issued to our actual API.

In the past I used another npm module, [talkback ](https://github.com/ijpiantanida/talkback), which transparently records both requests (with parameters) and responses to so-called "tapes" which I could then "playback" without the actual API.

Can mockoon do this? I read the guide here: https://mockoon.com/tutorials/requests-recording-auto-mocking/ but it's not very helpful. Am I doing something wrong?

**Comment by 255kb** [comment]
If you already have routes declared in Mockoon, your calls won't make it to the proxied server. The feature is here to create endpoints and not update them with additional information. 

The workflow is the following:

1. the route you want to automatically create is **not** declared in Mockoon (not present in the list under the Routes tab)
 
  ![image](https://github.com/mockoon/mockoon/assets/7489814/90454637-1916-4268-a13f-510d2c263c7e)

3. You enable the proxy mode and recording (which will automatically start the server)
  
  ![image](https://github.com/mockoon/mockoon/assets/7489814/17c3af32-d250-41df-af41-87fd9b064e6c)
  
  ![image](https://github.com/mockoon/mockoon/assets/7489814/847cc595-360a-48f0-bdd4-c0ba2313757d)

4. you call the endpoint you want to mock, let's say in my case `GET /users`, a route will automatically be created:
  
  ![image](https://github.com/mockoon/mockoon/assets/7489814/8b42184b-27af-4f17-a1e3-073db0a39306)

5. From now on, Mockoon will always answer with the route newly created and will never again forward your calls to `GET /users` to the proxied API, unless to toggle it off (but no additional route will be created): 

  ![image](https://github.com/mockoon/mockoon/assets/7489814/f786990a-e027-4cde-af12-ea5681548c33)

**Comment by digeomel** [comment]
@255kb thank you for your quick reply! Unfortunately it's not the workflow I was hoping for, but I'm sure it will be helpful for other users.
