### ISSUE TITLE
Sending ZIP breaks the archive

### ISSUE THREAD

**Issue by dominicrico** [255kb/mockoon#22]
Hey,

if I want to send a ZIP file I get following error when I try to unzip it:

`Error: invalid central directory file header signature: 0x80014`

If I test it with `unzip -tq Archive.zip` the output says:
```
error [Archive.zip]:  missing 113 bytes in zipfile
  (attempting to process anyway)
error [Archive.zip]:  start of central directory not found;
  zipfile corrupt.
  (please check that you have transferred or created the zipfile in the
  appropriate BINARY mode and that you have compiled UnZip properly)
```

**Comment by 255kb** [comment]
@dominicrico on which OS did you encounter this bug? 
Apparently it's something that can happens with Express but I have no problem with zip files on Windows

**Comment by dominicrico** [comment]
@255kb I'm working on High Sierra MacOS. Thanks for your help!

**Comment by 255kb** [comment]
@dominicrico v0.3.0 is out, files are sent differently now, maybe you can try again and let me know if the bug is still there :)
