### ISSUE TITLE
Routes with parameters

### ISSUE THREAD

**Issue by greimers** [255kb/mockoon#26]
Maybe I'm doing it wrong, but I don't get how to have a route with GET URL parameters like `http://localhost:3001/test?param=hello`. Is this not supported?

**Comment by 255kb** [comment]
Query params are not part of the route declaration. 
You define the route like this `http://localhost:3001/test` and then when you call you pass query params with `?param1=value&param2=value...`. 
But please note that for now the application is not reacting to these params at all. The response won't be customized at all. 
This feature is planned in the future #4, so I will close this ticket for now.

**Comment by hervehobbes** [comment]
Hello,

I also need this feature and without  it, Mockoon is pretty useless.
