### ISSUE TITLE
Save environment as JSON

### ISSUE THREAD

**Issue by gebeto** [255kb/mockoon#29]
Please add possibility to save your environment into JSON file(maby with other file type but with json structure inside, with that feature we can use **"Open In..."** select **Mockoon** by default to open environment file, it will be very-very-very useful feature), it will be a great feature if i want to save my environment in project repository and use it on other development machines

I really want to help you to improve this app, if you need some help, please write me😅 I can try to implement this functionality if you open sources for me or something like that

**Comment by 255kb** [comment]
Good idea. Import / export is definitely something on the list. 

The app may be open sourced soon so please stay tuned if you want to contribute.

**Comment by 255kb** [comment]
Closing this as duplicate of #7 ticket (will be part of export feature)
