### ISSUE TITLE
Add mockoon to homebrew for easy install and updates

### ISSUE THREAD

**Issue by fiveNinePlusR** [255kb/mockoon#31]

**Comment by 255kb** [comment]
I already thought about this but honestly I did not get how one can add a software to homebrew 😅 
The documentation is completely cryptic (maybe because I am not a mac user) 
So any guidance / help is welcomed

**Comment by danielbayerlein** [comment]
@255kb I think [Homebrew Cask](https://github.com/Homebrew/homebrew-cask) is the right place for mockoon. I can help you with this.

**Comment by 255kb** [comment]
@danielbayerlein Help is welcomed :) 
In the meantime I read a little bit about homebrew casks and I think I understood how it can be added. 
But I think there are some prerequisites for it to work with an Electron application. I will soon publish a new version and I will make sure that binaries are compatible with homebrew. Then we can add it :)

**Comment by 255kb** [comment]
PR has been merged, Mockoon should be available on brew now. 
Thanks for your help :)
