### ISSUE TITLE
Support overriding Content-Type header

### ISSUE THREAD

**Issue by techpavan** [255kb/mockoon#34]
**Describe the bug**
Content-Type header is currently chosen from a drop down which makes it limited in options. If it is defined again in the headers section, give priority to the custom value over the pre-defined drop down option.

**To Reproduce**
1. Define any http request and response
2. Add the header Content-Type with any value in the Headers section of response.
3. Start the mock server
4. Invoke the configured request from any HTTP client.
5. See that the custom header does not appear in the response

**Expected behavior**
Content-Type header configured in the Headers section of response should be given priority.

**Screenshots**
NA - simple to reproduce

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: any

**Comment by 255kb** [comment]
Hello, thanks for opening this issue, I will look into it in the next version. 
I was sure it was the existing behavior but now as I look in the code I can see that this is not the case! 😄

**Comment by 255kb** [comment]
More robust content type headers are coming in next release
