### ISSUE TITLE
Body template enhancement

### ISSUE THREAD

**Issue by eric23** [255kb/mockoon#35]
**Is your feature request related to a problem? Please describe.**
I may create different responses based on the input parameter from previous POST. E.g, I make a request like this: '\tag\ {id} \audience'. Then I want to create different response for each 'id'.
  
**Describe the solution you'd like**
A dynamic response template like this:

// switch({id})
'1': {audience:100},
'2': {audience:150},
'3': {audience:120}
/ switch

**Describe alternatives you've considered**
A random number generator is also workable. Just like this:

{
   audience: // random (number:3) /random
}

It returns a random number between 100-999.
**Additional context**
No.

**Comment by 255kb** [comment]
The switch helper will be in the next release. 
In the meanwhile you can use the existing random number generator as explained [here](https://github.com/webroo/dummy-json#integer)
