### ISSUE TITLE
Add support for 'oneOf' and 'someOf' to body templates

### ISSUE THREAD

**Issue by dlmh** [255kb/mockoon#36]
The dynamic body templating is already pretty awesome, but it would be even better if you could add support for 'oneOf' and 'someOf'.

The 'someOf' picks one or more items from any given array, with optional parameters defining the minimum and maximum amount of items to be picked, returning an array with the picked items. 

`"type": "{{someOf ["apple", "banana", "cherry", "orange"] 1 3}}"`

The 'oneOf' picks one single item from an array and returns the item.

`"type": "{{oneOf ["small", "medium", "large"]}}"`

**Comment by 255kb** [comment]
Nice idea, I will plan this for the next release.

**Comment by 255kb** [comment]
Will be in next release

**Comment by ondrovic** [comment]
This is a great feature but I cannot seem to get it to work correct
`"test": {{oneOf ["One", "Two","Three"]}}` - returns no errors or messages just white screen when refreshing
`"test2": {{oneOf "one"}}` - this works correctly it selects one letter outputs it

seems like it's ignoring anything that is in `[ ]`

using release  1.20
