### ISSUE TITLE
[Poll] Add more import / export formats

### ISSUE THREAD

**Issue by 255kb** [255kb/mockoon#38]
Please vote below with reactions (👍) for import / export formats you would like most to see in Mockoon. You can also comment to add other formats. 
Please keep this issue clean by using emojis and avoiding commenting too much.

**Comment by 255kb** [comment]
Open API https://github.com/OAI/OpenAPI-Specification

**Comment by 255kb** [comment]
Format compatible with [json-server](https://github.com/typicode/json-server)

**Comment by 255kb** [comment]
RAML format https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/

**Comment by 255kb** [comment]
HAR format

**Comment by bruce-bjss** [comment]
Use Swagger.io format

**Comment by 255kb** [comment]
@aosi87 It's definitely a go for Swagger / OpenAPI format (probably in the next update). Due to limited time I can spent working on this application I think it's the only format it will support for now. And other formats are definitely less popular.

**Comment by 255kb** [comment]
OpenAPI/Swagger format import implementation will be tracked in #86. Closing this ticket as no other format will be supported for now. 
Thank you all for voting 👍
