### ISSUE TITLE
Cursor automatically jumps to the end of the url when editing

### ISSUE THREAD

**Issue by Jancat** [255kb/mockoon#39]
**Describe the bug**
When editing somewhere in the url, the cursor automatically jumps to the end of the url. I had to reposition my cursor every time.

**To Reproduce**
1. Go to route editing panel
2. Click on somewhere in url input box(endpoint)
3. Input one character
4. See the cursor jumps to the end

**Expected behavior**
The cursor moves normally.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [MacOS 10.13.4]
 - Browser: [Chrome]
 - Version [v0.4.0 beta]

**Comment by 255kb** [comment]
will be corrected in next release 0.5.0, thanks for the contribution
