### ISSUE TITLE
Options request support

### ISSUE THREAD

**Issue by azizbodal** [255kb/mockoon#40]
I'd love to see an options request support.

**Comment by 255kb** [comment]
Could you elaborate on this please?
Mockoon is already answering with status 200 to all OPTIONS requests, would you like something more configurable? and if yes, how?

**Comment by azizbodal** [comment]
Currently, the route verbs supported are GET, PUT, POST, PATCH, DELETE, HEAD. I don't see an OPTIONS verb. This would be useful in testing different CORS behaviors based on the OPTIONS response.

**Comment by 255kb** [comment]
ok, I will plan this to allow OPTIONS custom OPTIONS routes but still keep a setting if one want Mockoon to handle OPTIONS requests automatically

**Comment by 255kb** [comment]
An environment option will be added in the next release. It will allow you to toggle automated OPTIONS handling.
If activated all OPTIONS routes not catched by you will be catched by Mockoon.
