### ISSUE TITLE
Ability to order routes by dragging a route up or down

### ISSUE THREAD

**Issue by azizbodal** [255kb/mockoon#41]
Mockoon supports a "/*" route that will handle all requests that were not previously routed, which is awesome, however you have to put this route at the end. Otherwise it will prevents subsequent routes from getting considered. To help organize the routing strategy, it would nice if we could reorder routes by dragging them up or down.

**Comment by azizbodal** [comment]
![image](https://user-images.githubusercontent.com/10204290/42459837-244a506c-8362-11e8-8803-6e44fb000083.png)

**Comment by 255kb** [comment]
This will be added in 0.5.0 release
