### ISSUE TITLE
Unable to put consecutive slashes in route path

### ISSUE THREAD

**Issue by mivanov** [255kb/mockoon#45]
**Describe the bug**
The route path does not allow consecutive (more than 1) slashes. This leads to a 404 if the route is requested with consecutive slashes in it. 

**To Reproduce**
1. Click on 'Add route'
2. In the path box try to type in or paste `foo//bar`
3. Observe that the input box now says `foo/bar` (slash was removed)
4. Start the server
5. Using an HTTP client request `http://localhost:3000/foo//bar`
6. Observe that you get a 404 Not found error instead of 200 OK.

**Expected behavior**
Either the server should allow routes with consecutive slashes or else transparently serve the route with the simplified path by removing consecutive slashes from incoming requests.

**Desktop (please complete the following information):**
 - OS: OSX
 - Version v0.4.0 beta

**Comment by mivanov** [comment]
Forgot to mention, I love Mockoon, thank you for this glorious thing!

**Comment by mivanov** [comment]
I have seen all variations, since it's up to the server or sometimes application, but I believe silently serving the route is most common. In my experience I would rank them like this in order from most common to least common:

1. `200`
2. `302`
3. `404`
4. `301` maybe, but I'm honestly not sure I have seen this.

I would be happy with a 200, or with allowing consecutive slashes so one could replicate any behavior.

**Comment by 255kb** [comment]
so what about:
1. define a route /test/xxxx
2. request it with /test////xxxx 
3. app convert it to /test/xxxx so you get the declared route with defined status without any redirection?

**Comment by mivanov** [comment]
That makes perfect sense and would solve the issue I had.

**Comment by 255kb** [comment]
ok, it's done, it will be released in v1.0.0 in the coming weeks (before end of August), thanks for your help 👍
