### ISSUE TITLE
UI Theming / Light colors

### ISSUE THREAD

**Issue by spike1234** [255kb/mockoon#46]
Is it possible to add light UI colors (or some way to define colors)? It's difficult to read: it's too dark.

**Comment by tmcdos** [comment]
I vote for this, too - please, at least change the grey color of the text to something more bright (e.g. the orange vertical line which designates the current environment in the leftmost column)

**Comment by 255kb** [comment]
Nice idea, I will plan this 👍

**Comment by 255kb** [comment]
Before working on different themes I will lighten everything a little bit in the next minor version, it's true that it's too dark!
