### ISSUE TITLE
Slow response time 

### ISSUE THREAD

**Issue by ozzie1998** [255kb/mockoon#48]
Response time for a basic response sourcing the body from a file is at least 2 seconds! Which isn't great. 

I've timed a bunch of requests:

+ 1: `1157ms` 
+ 2: `923ms`
+ 3 `485ms`
+ 4  `631ms`

Server response time should be under `200ms`

My payload: 

```js
[
	{
		"title": "Hello. Today is Thursday.",
		"body": "Finally, it’s nearly the weekend - not quite yet. But we’re now over the hump-day, and have two more days to go! ",
		"key": 1,
		"submitData": "By Ozzie - Thursday, 26th of July, 2018."
	},
	{
		"title": "Long title post components?",
		"body": "This is a complex matter, I like the short and snappy title, but I will need longer titles to make it work. ",
		"key": 2,
		"submitData": "By Ozzie - Thursday, 26th of July, 2018."
	},
	{
		"title": "This just keeps getting better",
		"body": "Important posts tag. Yep, a new tag that will be sorted so that they are at the top of the page, they will be more obvious, and will get a neat litle tag saying they're important",
		"key": 3,
		"submitData": "By Ozzie - Friday, 27th of July, 2018.",
		"important": false,
		"pinned": false
	},
	{
		"title": "Wanted to end today on a high.",
		"submitData": "By Ozzie, Sunday, 19th of July, 2018",
		"body": "The implementation for sorting pinned posts away from standard ordinary posts is simple: Pull them out, delete their entry in the main object, create a new array, and then just add them onto the start once the main array has been populated. But it's a tad slow.. And I don't know why :(",
		"pinned": true,
		"important": false,
		"key": 4
	},
	{
		"title": "What's to come...",
		"submitData": "By Ozzie, Sunday, 19th of July, 2018",
		"body": "Syntax highlighting and markdown support (either that or a custom language), a rewrite of the post generation components and general tidying up of the code base. Also, while it doesn't necessarily matter, post generation is a bit slow. Not sure why, but yeah it's not as quick as it is supposed to be, though I think I can address that with the rewrite.  ",
		"pinned": false,
		"important": false,
		"key": 5
	},
	{
		"title": "Hello World",
		"submitData": "Not sure of the date, this is just a test",
		"body": "Literally, this is just a test. I think the [There's More] button is broken",
		"important": false,
		"pinned": false,
		"key": 7
	},
	{
		"title": "Nearly finished the frontend!",
		"submitData": "Thursday, 16th of August, 2018",
		"body": "**This is just a test**\n Things that I need to complete:\n\n+ Post submit page \n\n+ The backend",
		"important": false,
		"pinned": false,
		"key": 8
	}
]
```

**Comment by 255kb** [comment]
Hi, I just tried with the same payload in a JSON file and it's under 10ms (Windows 10) and pretty stable (6.5ms, 7.5ms, 7.5ms...). Which OS are you using?

**Comment by ozzie1998** [comment]
MacBook Pro early 2011 latest Mac OS

**Comment by 255kb** [comment]
I tried to reproduce the bug on Sierra 10.13 with your file but I get pretty good results too, between 6 and 30ms.
I am not sure what is affecting the performances. Could you maybe send a screenshot of your environment ?

**Comment by ozzie1998** [comment]
Its running on High Sierra latest, with very little else running. I’ve
moved on to writing my own little server to serve JSON

**Comment by 255kb** [comment]
Sorry to hear that, I honestly don't know what can cause this latency. 
I will close as I can't reproduce the bug. 
This will / may be reopened when we have more information or a way to reproduce it.

**Comment by schidaine** [comment]
I can reproduce on MacOS Mojave. Using short 42 response for a GET /answer, I get a mean at 600ms, from 200ms to 1,5s. Can't explain why so far.

**Comment by abiodunjames** [comment]
I can reproduce this on MacOS mojave as well. The response time is too slow

**Comment by hmalatini** [comment]
Same here. Few days ago started to response with delay of avg 1 second. OS is Widnows 10

**Comment by hmalatini** [comment]
I fixed it disabling CORS feature. Now it works well. Probably there is something with the performance related with CORS

**Comment by 255kb** [comment]
Hi @hmalatini 
It is strange that disabling CORS feature solved the problem as it basically answers 200 to all OPTIONS calls. Nothing really fancy here. 
Also, I was never able to reproduce this or get any setup that allows me to do so. Do you use any third party software that could interfere, like Fiddler?

**Comment by hmalatini** [comment]
@255kb 
Yes, it is really weird. But is basically what I did for get responses fast again. I don't use any third party software that can interfere. If I can help you with something, just let me know

**Comment by 255kb** [comment]
Could you try to reproduce and send me the relevant data (through export menu) if possible. Also, knowing which app/browser you used to call the endpoints would be useful.
Thank you

**Comment by hmalatini** [comment]
Yes, I could reproduce it. In fact, I can realized of something weird. The solution has nothing to do with CORS. I made a video for show the steps that I did for reproduce it, and how I fixed it. Can we talk via email and I can show you what I did? For security reasons, I can't pass the mocked data that I did for test because it is confidentially of my company.
My browser is: Versión 86.0.4240.75 (Build oficial) (64 bits)

**Comment by hmalatini** [comment]
I have joined the spectrum chat! We can continue there! Thanks!

**Comment by bruce-c-liu** [comment]
Hi, has there been any updates on this? I'm on macOS Catalina. With latency set to 0, a simple GET is taking 6-1500ms. 😭

**Comment by 255kb** [comment]
hi @bruce-c-liu 
Unfortunately no, we were unable to reproduce this on our setups, nor to find a pattern. We don't get many reports of this issue, and it seems that it's not always the same problem among the reports: random slowness vs 2 seconds slowness on all calls.

**Comment by bruce-c-liu** [comment]
Hmm, that's unfortunate. FYI, restarting the environment at least fixes this issue for about 10 minutes. Then, the problem I had starts happening. Perhaps it's some kind of memory leak.

**Comment by 255kb** [comment]
While the app may not have the best performances I didn't notice any big memory leak under a normal usage (i.e. connected to a front-end app that perform requests like a normal front-end app 😄 ). Maybe under heavy load? What is you typical usage?

**Comment by meinto** [comment]
Same problem here. I have an environment with a single `POST` route. The response time is between 40ms and 1.5 seconds. But response times below 100ms are extremly rare. Mostly they are in a rage between 300ms & 1.5s.

I'm on MacOS Catalina.

**Comment by 255kb** [comment]
@meinto This issue is very strange. We investigate this from time to time and are unable to find a root cause. 
However, I found some discussions regarding slowness with NodeJS and DNS resolving on localhost. Have you tried calling the mock API with `http://127.0.0.1:port`, instead of `localhost`?
