### ISSUE TITLE
Export request logs

### ISSUE THREAD

**Issue by sudhakarnaidu** [255kb/mockoon#49]
**Is your feature request related to a problem? Please describe.**
Thank you for the logs tab feature. There is no way to export the request logs to a report/file.

**Describe the solution you'd like**
An option to export the request logs to a text/csv format.

**Describe alternatives you've considered**
Atleast a copy/paste option

**Additional context**

**Comment by 255kb** [comment]
Thank you for using Mockoon! 
I don't think that I will implement this kind of feature. I want to keep Mockoon simple to use and focused on mocking endpoints only. Request logs are only an help but definitely not the core of the application. So adding more features to this is not planned

**Comment by mivanov** [comment]
@255kb I was using an older version and wished I could see an access log. Imagine my delight when I updated to the new version and saw the "Environment logs" button! This tool is rapidly replacing a lot of kludgy Node scripts and one-offs I always used to write for mocking HTTP, which is a huge productivity boost. As to this feature request, I don't need a way to export the logs, but I would second the alternative of being able to select and copy the text from the log. Is it possible without a lot of work, by setting some options or using a text box control? Would be happy to send a PR if it sounds ok.

**Comment by 255kb** [comment]
Thanks for using mockoon, I am glad you like it! 

Concerning the possibility of selecting the logs there is an open issue that you can upvote. It's not something big at all just some CSS.
