### ISSUE TITLE
v1.0.0 crashes on launch on Linux

### ISSUE THREAD

**Issue by ChrisAJS** [255kb/mockoon#50]
**Describe the bug**
After downloading the AppImage from the website and attempting to run the application; after the initial integration dialog, the following output appears in the console and the application fails to launch.

```
module.js:472
    throw err;
    ^

Error: Cannot find module '/tmp/.mount_mockoodTGR9I/resources/electron.asar/browser/init.js'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:431:7)
    at startup (bootstrap_node.js:155:9)
    at bootstrap_node.js:551:3
```

**NOTE: removing ~/.config/mockoon had no effect**

**To Reproduce**
1. Download Mockoon 1.0.0 AppImage
2. chmod a+x the AppImage file
3. Execute the AppImage file

**Expected behavior**
Application should launch providing mocky goodness for all

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Linux Fedora 28

**Additional context**
0.4.0 AppImage ran and continues to run fine.

**Comment by 255kb** [comment]
Hi, thank you for the bug report and sorry for the annoyance. 
I juste uploaded a new AppImage (in github release and .com website), could you please download it and test if it's working, for me it's working on Ubuntu 18.

**Comment by ElFeesho** [comment]
No annoyance at all! Happy to help- you've done a cracking job with the tool, I'll give it another download.

**Comment by ChrisAJS** [comment]
No annoyance at all! Happy to help- you've done a cracking job with the tool, I'll give it another download.

**Comment by ChrisAJS** [comment]
Working as intended from the Github releases page. Thanks for the quick turn around time!

**Comment by 255kb** [comment]
Perfect, thank you! 
It was apparently a bug in electron-builder version I was using (which was the latest when I started working on v1.0.0, but now it was 15 versions behind 😓 things are going too fast)

**Comment by ChrisAJS** [comment]
You turn around time was quite quick too though, so I don't think you have to worry too much about keeping up :+1:
