### ISSUE TITLE
Insert Array in header

### ISSUE THREAD

**Issue by GregoireSion** [255kb/mockoon#51]
i'm trying to make mockoon answer to an URL which contains an array in the header:

url?date=2018-05-06&**actors=RIRI&actors=FIFI&actors=LOULOU**
this might already be possible but i can't seem to find how in the doc or make it work myself

![capture](https://user-images.githubusercontent.com/26252906/44661353-f2c8d900-a9f9-11e8-8107-313751852632.PNG)
this is what i tried so far

This is a very coonvenient app, great job by the way

**Comment by 255kb** [comment]
Hi thank you for using Mockoon :)

This is currently not supported. Only the body supports [JSON templating](https://github.com/255kb/mockoon/wiki/%7B-%7D-JSON-templating) with a various range of helpers giving you access to URL params, query params etc. 
Headers values are not dynamic. 

This is an interesting feature. I will plan this for a future release.

**Comment by GregoireSion** [comment]
I see ! So as of now there is no way mockoon can understand the Url i'm submitting ?

**Comment by 255kb** [comment]
It can but only in the response body where you can write something like: 

```
{
  "response": "{{queryParam 'paramName'}}"
}
```

This syntax is not supported in the headers.

**Comment by 255kb** [comment]
Templating in headers will be in v1.2.0.
In the meantime, query params arrays are already working. If you add `{{queryParam 'test'}}` in the body, and call the route with `?test=a&test=b&test=c` you will get `a,b,c` printed.
