### ISSUE TITLE
Environment log is empty

### ISSUE THREAD

**Issue by kladis** [255kb/mockoon#53]
**Describe the bug**
Environment log is empty, even I see a response in my web browser.
I dont see any request info. Totally blank page.

**Desktop (please complete the following information):**
Mac OS X

Let me know how to diagnose to provide more detailed info...

**Comment by 255kb** [comment]
Could you please give more details about your setup (browser, etc)? 
It's working quite well for me under Sierra 10.13.1 with Mockoon v1.0.0 
![capture](https://user-images.githubusercontent.com/7489814/44814764-f61cba00-abdd-11e8-9030-0e6a8ad39b3a.png)

**Comment by kladis** [comment]
I'm sorry for this false issue. 
I rebooted my laptop and it's all right now.
Probably it's an OS X bug or something like this. Happens.

Thanks for the perfect tool!

**Comment by 255kb** [comment]
No problem, I couldn't reproduce it on any of my devices, so I am glad it's solved 😄 

Thank you for using Mockoon 👍

**Comment by kladis** [comment]
Hello! 

Just a small question (I didn't find any info, but looked). 

Is it possible to view I/O (or just an environment log) in PROXY mode?

Like catch/log all requests and watch it in the log tab? Possible?

**Comment by 255kb** [comment]
Normally everything is logged (even the favicon.ico request that the browser does when getting the URL). You will see on each log entry a little green tick that indicates if the request was catched by mockoon or not
