### ISSUE TITLE
POST call return 504

### ISSUE THREAD

**Issue by VinceRao** [255kb/mockoon#60]
**Describe the bug**
All the POST call return 504

**Desktop (please complete the following information):**
 - OS: Mac OS10.13.6

**Comment by 255kb** [comment]
Hi, I just tested on Mac OS 10.13.6 various POST routes and all of them answered with the correct status / body / headers.
Could you please maybe send more information about how you configured the route so I can try to reproduce?

**Comment by VinceRao** [comment]
I am just using the proxy mode without any mocks.
All the POST calls return 504 and it happens when I use express and http-proxy-middleware to create a proxy also.
But I found a solution in [https://github.com/chimurai/http-proxy-middleware/issues/40#issuecomment-249430255](https://github.com/chimurai/http-proxy-middleware/issues/40#issuecomment-249430255)
Not sure it helps or not.

**Comment by 255kb** [comment]
Nice catch! Apparently putting body parser before proxy middleware causes the body to not being proxied. Body parser was introduced in v1.0.0 and I didn't retest all proxy test cases. I will correct this in the next release.

**Comment by 255kb** [comment]
This will be in the next release v1.1.0
