### ISSUE TITLE
Can we have cloud deployable artifacts, which can be fit on cloud foundry/docker etc? 

### ISSUE THREAD

**Issue by vjain143** [255kb/mockoon#61]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by 255kb** [comment]
I think this feature while great is too much work to be implemented right now or in a near future. I would like first to focus on the desktop app itself. If this is a recurring request I will reconsider.
