### ISSUE TITLE
Support default header Content-Type

### ISSUE THREAD

**Issue by alonbhaim** [255kb/mockoon#64]
I'm trying to get a path from request body without sending content-type on header, although the body is valid JSON but mockoon identify it as text/plain.
Is there way to change the default content-type from text/plain to application/json?

**Comment by 255kb** [comment]
There is currently no way to set the entering request content-type.
I will definitely plan this as I faced the same issue :) 
What would be the more useful and / or logical ?
1. auto detecting and always parsing the body (if JSON is valid)
or
2. adding an option to set the default entering request Content-Type to JSON (checkbox) if none has been provided and only parse body if this option has been activated
