### ISSUE TITLE
Incoming Request Logging

### ISSUE THREAD

**Issue by dpjayasekara** [255kb/mockoon#74]
Is there an incoming request logging feature in Mockoon yet (or planned)? If not, I think it's an absolutely necessary feature to implement( log request method, url, headers, body etc.) since it will be very helpful in debugging in most of the cases.

**Comment by 255kb** [comment]
Yes there is one! 
It's per environment, just click on the clock in the upper right corner.

**Comment by dpjayasekara** [comment]
Oh. There it is! Thanks.
