### ISSUE TITLE
Support of json templating on files

### ISSUE THREAD

**Issue by pabloubal** [255kb/mockoon#80]
I'm currently experiencing an issue when trying to serve responses from a file, and it's that json templating doesn't work when using this model. If I serve the same response writing it inside the IDE, it works perfectly.

i.e. Response:
{
    "test": "{{guid}}"
}

If I write this in the Body section of the IDE I get the following response:
$ curl localhost:3000
{"test":"c754fae3-a952-4f27-aabd-2ba3b7645fe0"}

Instead, if I serve this from a file I get the following response:
$ curl localhost:3000
{
    "test": "{{guid}}"
}

**Comment by 255kb** [comment]
Good idea, it's sure that for now templating is not interpreted into files. Currently I am working on this ticket #52 which add support for templating in file path (so you can dynamically request files) and I will add the option to directly use file content as body. 
I will plan your feature for the next release also, as it make sense to do all these improvements together
