### ISSUE TITLE
[Question] Relative paths for files?

### ISSUE THREAD

**Issue by fjcalzado** [255kb/mockoon#84]
Is there a way that files can be saved in the JSON configuration with relative path? Otherwise the JSON could not be shared among devs. Thanks!

**Comment by 255kb** [comment]
This will be possible in the next release. 
The file path won't be stored as a relative path by default (which could cause problems on windows with multiple hard drives). But in the next release the file input is editable and supports templating, so you will be able to directly write "./file.json", and it will be saved like this. 
Keep in mind that the path will be relative to Mockoon executable.
