### ISSUE TITLE
Third party software import

### ISSUE THREAD

**Issue by 255kb** [255kb/mockoon#9]
Investigate how Postman (or other softwares) envs could be imported

**Comment by gwelr** [comment]
May I suggest the support for importing the RAML compliant files ? 

See RAML Specification here: https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md/

See a RAML example file here: https://github.com/mulesoft/api-console/blob/master/test/test.raml

**Comment by 255kb** [comment]
Closing this as duplicate of #7
