### ISSUE TITLE
[Question] How to run the test script?

### ISSUE THREAD

**Issue by Manikkumar1988** [255kb/mockoon#91]
Can you please add more steps to run the tests on contributing template?

I tried with npm run test but below error is thrown:

```
14 01 2019 18:00:14.545:ERROR [config]: File /Users/mypath/Documents/mockoon/mockoon/karma.conf.js does not exist!
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mockoon@1.3.0 test: `ng test`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the mockoon@1.3.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/mypath/.npm/_logs/2019-01-14T12_30_14_566Z-debug.log
```

**Comment by 255kb** [comment]
There are currently no karma tests (it's still the default Angular config, and I don't know if it still works). 
But I wrote a bunch of integration tests done with [Spectron](https://github.com/electron/spectron). You can run them with `npm run test-spectron`.

They should be run by CircleCI automatically when you open a pull request.
I will add more info on this in the contribution document. 

Also for this type of questions do not hesitate to use chat on the Community website: https://spectrum.chat/mockoon

**Comment by Manikkumar1988** [comment]
The command works! Just documenting that Out of 13, 4 passes on Mac OS

**Comment by 255kb** [comment]
Yeah I know, i have the same problem on CircleCI, I need to correct the tests, it's just a race condition, I think a problem during the loading of the data.
